# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: Dev Build
on:
  push:
    branches: [ '*' ]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - run: ./gradlew build --stacktrace --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts from ${{ github.sha }}
          path: build/libs/
